In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df=pd.read_csv('Restaurant_Reviews.tsv',sep='\t')
df

Review  Liked
0                             Wow... Loved this place.      1
1                                   Crust is not good.      0
2            Not tasty and the texture was just nasty.      0
3    Stopped by during the late May bank holiday of...      1
4    The selection on the menu was great and so wer...      1
..                                                 ...    ...
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

[1000 rows x 2 columns]

In [3]:
import nltk
from nltk.corpus import stopwords
from wordcloud import WordCloud 

In [4]:
def remove_punctuation(text):
    final = "".join(u for u in text if u not in ("?", ".", ";",":",  "!",'"'))
    return final


df['Review'] = df['Review'].apply(remove_punctuation)

nltk.download('stopwords')
stop_words = stopwords.words('english')
df['Review'] = df['Review'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop_words)]))

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [13]:

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.pipeline import Pipeline
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB

In [6]:
X=df['Review']
y=df['Liked']

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1)

# 1.svc with pipeline

In [8]:
pipe=Pipeline([('vectorize',CountVectorizer() ), ('classify',LinearSVC())])

In [9]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('vectorize', CountVectorizer()), ('classify', LinearSVC())])

In [10]:
y_pred=pipe.predict(X_test)

In [11]:
from sklearn.metrics import confusion_matrix,classification_report

cf=confusion_matrix(y_test,y_pred)
cf

array([[102,  32],
       [ 23,  93]], dtype=int64)

In [12]:
pipe.predict( ["The selection on the menu was great and so were the prices"])

array([1], dtype=int64)

# 2.multinomial nb with pipeline

In [15]:
pipe2=Pipeline([('vectorize',CountVectorizer() ), ('classify',MultinomialNB())])
pipe2.fit(X_train,y_train)
y_pred=pipe2.predict(X_test)
from sklearn.metrics import confusion_matrix,classification_report

cf=confusion_matrix(y_test,y_pred)
cf

array([[95, 39],
       [26, 90]], dtype=int64)

In [16]:
pipe2.predict( ["The selection on the menu was great and so were the prices"])

array([1], dtype=int64)

In [17]:
pipe.score(X_test,y_test)

0.78

In [18]:
pipe2.score(X_test,y_test)

0.74

In [19]:
import joblib

In [20]:
joblib.dump(pipe,'my_model.joblib')

['my_model.joblib']

In [21]:
samepipe=joblib.load('my_model.joblib')

In [22]:
samepipe.predict(["The selection on the menu was great and so were the prices"])

array([1], dtype=int64)